version: "3.5"
services:

    mysql:
        container_name: mysql
        image: mysql:5.7
        ports:
            - '3312:3306'
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=boomerphpmvc
            - MYSQL_USER=phpmyadmin
            - MYSQL_PASSWORD=123456
        volumes:
            - './bin:/docker-entrypoint-initdb.d/'
    apache2php7:
        container_name: apache2php7
        depends_on:
            - mysql
        build:
            context: .
            dockerfile: dockerfile
        ports:
            - "5003:80"
networks:
    default:
        external:
            name: nginxrpgateway_default              
